# Generated by Django 3.2 on 2022-03-04 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='STATUS',
            new_name='status',
        ),
    ]
